// <auto-generated />
using System;
using AspCoreStudy.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspCoreStudy.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210126045252_BancoInicial")]
    partial class BancoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("AspCoreStudy.Models.Palavra", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("dataAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("pontuacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Palavras");
                });
#pragma warning restore 612, 618
        }
    }
}
