// <auto-generated />
using System;
using AspCoreStudy.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AspCoreStudy.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("AspCoreStudy.Models.Palavra", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("dataAlteracao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<int>("pontuacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Palavras");
                });
#pragma warning restore 612, 618
        }
    }
}
